version: '3.1'

services:
  ant_server:
    image: docker.luzifer.cloud/antmediaserver:latest
    restart: always
    container_name: ams_server 
    volumes: 
      - ${LOG_PATH}:/usr/local/antmedia/log  
    environment:
      VIRTUAL_HOST: ${V_HOST}
      VIRTUAL_PORT: ${V_PORT}
      LETSENCRYPT_HOST: ${LE_HOST}
      LETSENCRYPT_EMAIL: ${LE_EMAIL}          
    ports:
      - 9999:9999
    expose:
      - "5080"
    networks:
      - proxy
   
networks:
  proxy:
    external:
      name: nginx-proxy
    